apiVersion: v1
kind: Namespace
metadata:
  name: raiaas-ipfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-node
  namespace: raiaas-ipfs
spec:
  serviceName: ipfs-node
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-node
  template:
    metadata:
      labels:
        app: ipfs-node
    spec:
      containers:
        - name: ipfs
          image: ipfs/go-ipfs:v0.26.0
          env:
            - name: IPFS_PATH
              value: "/data/ipfs"
          ports:
            - containerPort: 5001
              name: api
            - containerPort: 8080
              name: gateway
          volumeMounts:
            - name: ipfs-data
              mountPath: /data/ipfs
  volumeClaimTemplates:
    - metadata:
        name: ipfs-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  namespace: raiaas-ipfs
spec:
  ports:
    - port: 5001
      targetPort: 5001
      name: api
    - port: 8080
      targetPort: 8080
      name: gateway
  selector:
    app: ipfs-node
